### ISSUE TITLE
Different package names (npm and github repo)

### ISSUE THREAD

**Issue by alabeduarte** [cakecatz/rss-parser-promise#1]
Hi there,

I was not able to find the npm package of this project. I found `rss-parse-promise` instead of `rss-parser-promise` [here](https://www.npmjs.com/package/rss-parse-promise)

Assuming that they are the same, I would suggest you to change some of their names. On the README.md says that the usage is:

``` javascript
require 'rss-parser-promise'
```

But when I downloaded the package through npm, the one that worked was:

``` javascript
require 'rss-parse-promise'
```

Please, share your thoughts. I'm available to send some pull requests if you agree with this approach. Just tell me it's make sense.

And you did a nice job with it, by the way.

Thanks!

**Comment by cakecatz** [comment]
@alabeduarte 
Oops, I made a mistake :sweat_smile: 

I think change repository name into `rss-parse-promise`  and patching `README.md` are good.
I am glad if you create PR!

Thanks!

**Comment by alabeduarte** [comment]
Cool,

Just did: [Fix package name](https://github.com/cakecatz/rss-parse-promise/pull/2)
